name: Archiving CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_pdf_export:
    runs-on: ubuntu-latest
    container:
      image: jupyter/minimal-notebook:42f4c82a07ff
      options: --user 0

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Convert to PDF
      run: jupyter nbconvert --to pdf Data-analysis.ipynb
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: PDF-Export
        path: Data-analysis.pdf