name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_docker_image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        pull: true
        push: true
        tags: m6121/ords-reproducible-data-science:latest,m6121/ords-reproducible-data-science:${{ github.sha }}



  re-execute_nb:
    runs-on: ubuntu-latest
    container:
      image: m6121/ords-reproducible-data-science:${{ github.sha }}
      options: --user 0

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Re-execute notebook
      run:
        - papermill Data-analysis.ipynb Data-analysis_re-executed.ipynb
        - jupyter nbconvert --to pdf Data-analysis_re-executed.ipynb
        - nbdiff -s -o -a -d Data-analysis.ipynb Data-analysis_re-executed.ipynb > Data-analysis_diff
        - if [[ $(cat Data-analysis_diff) ]]; then echo "*Re-executed notebook is different to uploaded one*"; exit 1; fi
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Re-execute Notebooks
        path: |
          Data-analysis_re-executed.ipynb
          Data-analysis_re-executed.pdf

  parameterise_nb:
    runs-on: ubuntu-latest
    container:
      image: m6121/ords-reproducible-data-science:${{ github.sha }}
      options: --user 0

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Parameterise notebook
      run: for i in 2 3 5 8 13; do papermill -p kmeans_k ${i} Data-analysis.ipynb Data-analysis_parameterised_${i}.ipynb; jupyter nbconvert --to pdf Data-analysis_parameterised_${i}.ipynb; done
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Parameterised Notebooks
        path: |
          Data-analysis_parameterised_*.ipynb
          Data-analysis_parameterised_*.pdf
